name: Secret scan

on:
  push:
    branches: [ main, 'security/**' ]
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Secret pattern scan
        run: |
          set -e
          echo "Scanning staged files for common secret patterns..."
          # Find changed files in this commit/PR
          git fetch --no-tags --depth=1 origin ${{ github.ref }} || true
          files=$(git diff --name-only ${{ github.sha }} || git ls-files)
          exit_code=0
          for f in $files; do
            # skip binary files
            if file --brief --mime-type "$f" | grep -qv text; then
              continue
            fi
            # patterns to check
            if grep -nE "AIzaSy[0-9A-Za-z_-]{35}" "$f"; then
              echo "Found Google API key pattern in $f"; exit_code=2
            fi
            if grep -nE "AKIA[0-9A-Z]{16}" "$f"; then
              echo "Found AWS Access Key pattern in $f"; exit_code=2
            fi
            if grep -nE "xox[baprs]-[0-9A-Za-z-]{10,}" "$f"; then
              echo "Found Slack token pattern in $f"; exit_code=2
            fi
            if grep -nE "-----BEGIN (RSA|PRIVATE) KEY-----" "$f"; then
              echo "Found private key in $f"; exit_code=2
            fi
          done
          if [ $exit_code -ne 0 ]; then
            echo "One or more secret patterns were found. If this is a false positive, update the workflow or whitelist files."
            exit $exit_code
          fi
          echo "No common secret patterns found."
